version: '3.8'

services:
  web:
    image: home_monitoring/httpserver:1.0
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    env_file:
      - .env
    networks:
      - mynetwork

  pgdb:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge