"""enforce uniqueness on plant and room names

Revision ID: 273de061e607
Revises: 
Create Date: 2024-02-24 16:03:23.800103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273de061e607'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_plant_name', 'plant', ['name'])
    op.create_unique_constraint('uq_room_name', 'room', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_room_name', 'room', type_='unique')
    op.drop_constraint('uq_plant_name', 'plant', type_='unique')
    # ### end Alembic commands ###
