"""a plant can have multiple sensors

Revision ID: b1e436844f10
Revises: 273de061e607
Create Date: 2024-03-02 15:53:01.137571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e436844f10'
down_revision: Union[str, None] = '273de061e607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    #create a catch all plant and rooms for which the name is unknown
    op.execute("INSERT INTO room VALUES (0, 'catch all room')")
    op.execute("INSERT INTO plant VALUES (0, 0, 'catch all plant')")
    #replace NULLs with the catch all plant
    op.execute("UPDATE plant_sensor SET plant_id = 0 WHERE plant_id is NULL")
    op.alter_column('plant_sensor', 'plant_id',
               existing_type=sa.INTEGER(),
               nullable=False)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_sensor', 'plant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
